language: go
go:
- 1.4
install:
- go get -u -v github.com/spf13/hugo
script:
- hugo -d $DEPLOY_DIR
- openssl aes-256-cbc -K $encrypted_5172ec3b3f0f_key -iv $encrypted_5172ec3b3f0f_iv -in $DEPLOY_KEY.enc -out $DEPLOY_KEY -d
- chmod 600 $DEPLOY_KEY
- eval $(ssh-agent)
- ssh-add $DEPLOY_KEY
- git remote set-url origin git@github.com:$TRAVIS_REPO_SLUG.git
- ./deploy.sh
- rm -f $DEPLOY_KEY
env:
  global:
  - DEPLOY_DIR=public
  - DEPLOY_KEY=deploy_key.pem
