language: go
go:
- 1.8
install:
- go get -u -v github.com/gohugoio/hugo
- go get -u -v github.com/tdewolff/minify/cmd/minify
script:
- hugo -d $DEPLOY_DIR
- minify -r -o $DEPLOY_DIR $DEPLOY_DIR
env:
  global:
  - DEPLOY_DIR=public
deploy:
  provider: s3
  bucket: kuune.org
  skip_cleanup: true
  local_dir: "$DEPLOY_DIR"
  access_key_id:
    secure: aIFzhNZvgjterusAFE7rDbIZ18jpWr2aRDJ0QUWTlFT8RWO/JWJslcOsn3fxmVGjrkkkB6MHVyTX3PucYDl64yD+Aiow3d3jJn1IEN1DVGmTCAzdyYHr26GUq4C7VrE1WXykE4mYgOtaLCCVjHNoODBRxWGRoHc0lF+3iauqQ1w=
  secret_access_key:
    secure: bIAAEmCa0hXJX7q1M8W/VnLTemw09DRVNQ0RoOy1qyg5C6PBWoFhDNS030u2HfswdPeRoD2pH6eaqnjicDh+eLU0r6g8RHz2ai6G7jyT365gONhvHET7To588Xx5LkuFQZyKPPfWRHT2VOZTbrXek2OJAb1Y1aelY5tl5sYptBQ=
notifications:
  email:
    on_success: always
    on_failure: always
