language: go
go:
- 1.11
script:
- bash build.sh
env:
  global:
  - secure: Ah3SeBJK8N4j56kLo0YbznpndvZmcOjQgFoWeVdNQ50PnXFhe8Ix8I+aFkSc/eUKSeWIxTaLu1+LfmDdRFFnfDAXbMvhjLm7ALJLVsetdcrnLH9IZYtOL5H5laVwm9VB6n7Jjgyg2dGTtzmeHVlryUNDeBUJm7RLDEMIUJ4EES4=
  - secure: NgTkbZnIwk0AmhgVPv3G4pPmuLimDUnYdfzv7CYljIzAcFYfDzMnkxfwgWL3YzHM7pa9ZmFkwlyq0Izg5izo8N+xCqMQE9r05z9QvsoAi+MKPiOdi0xP/0yavZA/Ntk0Zxi/ehtn7PXa33SjkwB0fs7w2SaWdiKrBA3pNI2x2eM=
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
notifications:
  email:
    on_success: always
    on_failure: always
