baseurl = "https://kuune.org/"
languageCode = "ja-jp"
title = "kuune.org"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
paginatepath = "p"
disableHugoGeneratorInject = true
pygmentsCodefences = true
pygmentsUseClasses = true
enableGitInfo = true

[frontmatter]
  date = ["date"]
  lastmod = [":git"]

[permalinks]
  text = "/:section/:year/:month/:day/:filename/"

[taxonomies]
"text/tag" = "text/tags"

[blackfriday]
  extensions = ["hardLineBreak", "Footnotes"]

[params.titles]

[params.header]

[params.links]

[params.twitter]
  user = "naoina"
  url = "https://twitter.com/naoina"

[params.github]
  user = "naoina"
  url = "https://github.com/naoina"

[params.facebook]
  appid = "1711329939155199"

[params.disqus]
  text = "kuune"

[params.bitcoin]
  address = "3GZuMjKHrDaSD4mAkn5qV5UnWpwLavahBM"
[params.monacoin]
  address = "MPiZxekuRqdCmE9qoRs2v5YJcUgARLSXez"

[params.amazon]
  url = "https://www.amazon.co.jp/registry/wishlist/TE72PDXI8Z2Y/"
