baseurl = "https://kuune.org/"
languageCode = "ja-jp"
title = "kuune.org"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
disableHugoGeneratorInject = true
pygmentsCodefences = true
pygmentsUseClasses = true
enableGitInfo = true

[pagination]
path = "p"

[frontmatter]
  date = ["date"]
  lastmod = [":git"]

[permalinks]
  text = "/:section/:year/:month/:day/:filename/"

[taxonomies]
"text/tag" = "text/tags"

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[imaging]
  resampleFilter = "lanczos"
  quality = 92

[params.titles]

[params.header]

[params.links]

[params.twitter]
  user = "naoina"
  url = "https://twitter.com/naoina"

[params.github]
  user = "naoina"
  url = "https://github.com/naoina"

[params.facebook]
  appid = "1711329939155199"

[params.disqus]
  text = "kuune"
