baseurl = "https://kuune.org/"
languageCode = "en-us"
title = "kuune.org"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
paginatepath = "p"
disableHugoGeneratorInject = true

[permalinks]
  text = "/:section/:year/:month/:day/:filename/"

[taxonomies]
tag = "tags"

[blackfriday]
  extensions = ["hardLineBreak", "Footnotes"]

[params.titles]

[params.twitter]
  user = "naoina"
  url = "https://twitter.com/naoina"

[params.github]
  user = "naoina"
  url = "https://github.com/naoina"

[params.facebook]
  appid = "1711329939155199"

[params.disqus]
  text = "kuune"
