baseurl = "https://kuune.org/"
languageCode = "en-us"
title = "kuune.org"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
paginatepath = "p"
disableHugoGeneratorInject = true

[permalinks]
  text = "/:section/:year/:month/:day/:filename/"
  money = "/:section/:year/:month/:day/"

[taxonomies]
tag = "tags"

[blackfriday]
  extensions = ["hardLineBreak", "Footnotes"]

[params.titles]
  money = "不労所得への道"

[params.header]
  money = { color = "#fff", background = "#000" }

[params.links]
  text = [
    { name = "不労所得への道", url = "https://kuune.org/money/" }
  ]
  money = [
    { name = "kuune.org", url = "https://kuune.org/text/" },
  ]

[params.twitter]
  user = "naoina"
  url = "https://twitter.com/naoina"

[params.github]
  user = "naoina"
  url = "https://github.com/naoina"

[params.facebook]
  appid = "1711329939155199"

[params.disqus]
  text = "kuune"
  money = "money-kuune-org"
