name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - config.toml
      - build.sh
      - deploy.sh
      - 'content/**'
      - 'layouts/**'
      - 'assets/**'
      - 'static/**'
      - .github/workflows/*.yml
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: gohugoio/hugo
        path: hugo
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - run: echo "${GOPATH}/bin" >> $GITHUB_PATH
    - run: (cd hugo; CGO_ENABLED=1 go install --tags extended)
    - run: ./build.sh
    - run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
