name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - config.toml
      - build.sh
      - deploy.sh
      - 'content/**'
      - 'layouts/**'
      - 'assets/**'
      - 'static/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: echo "::add-path::${GOPATH}/bin"
    - run: ./build.sh
    - run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
